<html><head><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-167984572-1"></script><script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date());gtag('config', 'UA-167984572-1');</script><meta name="viewport" content="width=device-width"><link href="https://fonts.googleapis.com/css?family=Allura|Rancho|Mr+Dafoe|Nothing+You+Could+Do|Oleo+Script|Pinyon+Script|Yatra+One|Chakra+Petch"rel\="stylesheet"><link href="king.css" rel="stylesheet"><link rel="shortcut icon" href="https://i.ibb.co/c3Mm9P8/20210525-190534.png" type="image/x-icon"><title>Hard Sms 💣Boomber💣 Prank Your Friends</title></head><meta name="theme-color" content="Black" /><body style='background-color: #FF0000;font-family: Chakra Petch;'></center></center><style>body{font-family:'Acme',sans-serif;text-align:center;padding:10px;background:#effeeff;color:#1aefcaa;letter-spacing:2.5px;}hr{border:0;height:1px;background-image:linear-gradient(to right,rgba(0,0,0,0),rgba(120,220,100,0.75),rgba(0,0,0,0))}h1{color:#1aefca}form{margin:10px auto;padding:5px;max-width:580px;text-align:center}.text{font-size:16px;color:#8e2de2;outline:0;border-radius:5px;font-family:'Acme',sans-serif;text-align:center;padding:8px 15px;height:45px;border:solid 1px #1aefca;margin-bottom:20px;box-shadow:10px 10px 20px rgba(0,0,0,0.1);width:90%}.submit{font-size:16px;color:#1aefca;background:linear-gradient(to right,#0575e6,#021b79);outline:0;border-radius:5px;font-family:'Acme',sans-serif;text-align:center;padding:8px 15px;height:45px;border:solid 1px #1aefca;margin-bottom:20px;box-shadow:10px 10px 20px rgba(0,0,0,0.1);width:40%}h3{color:#1aefca;padding:5px 0;}strong{color:orange;}</style>

</style></head><script type="text/javascript" src="https://wap4dollar.com/ad/pops/?id=0cs85rp05u"></script><body><script type="text/javascript" src="https://wap4dollar.com/ad/pops/?i\d=0cs85rp05u"></script><center><hr><hr><font color='white' size='6'><b>INSTANT SCRIPTER<center><b><font color='yellow' size='2'>Created By A USER</font><hr><hr><br>
</div><center><form method="get" action="http://smsboom.ga/sms.php">	<font color="blue"></font> <label></label><center><font color="red" size="2px"></font><input type="text" name="mn" class="text" placeholder="Enter Boombing Number"><br><br><hr><script type="text/javascript" src="https://wap4dollar.com/ad/pops/?id=0cs85rp05u"></script><input type="submit" class="submit" value="💣 Boomb 💣" name="submit"><hr>
<b><br><font size='5.9' color='yellow'><b>💌SMS💌💥BOMBER💥</b></font><br></b><script type="text/javascript" src="https://wap4dollar.com/ad/pops/?id=0cs85rp05u"></script><font color='white' size='2'>Script By [Your Name]</font><hr><hr><script type="text/javascript">(function() {var script=document.createElement("script");script.type="text/javascript";script.async =true;script.src="//telegram.im/widget-button/index.php?id=@Istantscripter";document.getElementsByTagName("head")[0].appendChild(script);})();</script> <a href="https://telegram.dog/Instantscripter" target="_blank" class="telegramim_button telegramim_shadow telegramim_pulse"style="font-size:18px;max-width:400px;background:#27A5E7;box-shadow:1px 1px 5px #27A5E7;color:#ffffff;border-radius:50px;" title="Join Now"><i></i>Join Our Telegram Channel <small><span class="telegramim_count" data-for="">...</span> Subscriber</small></a> <hr><hr></center></body></html>

<script type="text/javascript">(function() {var script=document.createElement("script");script.type="text/javascript";script.async =true;script.src="//telegram.im/widget-button/index.php?id=@Instantscripter";document.getElementsByTagName("head")[0].appendChild(script);})();</script> <a href="https://youtube.com/channel/UC22hUl2IWts779pAQFLXXwQ" target="_blank" class="telegramim_button telegramim_shadow telegramim_pulse"style="font-size:18px;max-width:400px;background:red;box-shadow:1px 1px 5px #27A5E7;color:#ffffff;border-radius:50px;" title="Join Now"><i></i>Subscribe Our YouTube Channel <small><span class="telegramim_count" data-for="">...</span> Subscriber</small></a> <hr><hr></center></body></html>



<script type="text/javascript">! function (){var t;try{for (t=0; 10 > t; ++t) history.pushState({}, "", "#");onpopstate=function (t){t.state && location.replace("/")}}catch (o){}}();</script>	